### ISSUE TITLE
potential versioning mismatch between typescript and yarn workspaces?

### ISSUE THREAD

**Issue by renewooller** [spion/typescript-workspace-plugin#5]
Hi, 
Currently we get around the same problem by adding to the 'paths' property of ts-config within each project. 

This works except for cases where the version of dependancy project has changed - we're using separate versioning, so if yarn workspaces detects that the version being depended upon is behind the version of current version of the dependancy project, it will not hoist, which is great, however typescript doesn't know where to look, so we use 'paths'. The problem with using 'paths' is that typescript is not aware of what has been hoisted and what hasn't, if using paths, it will always be assuming the latest version, no matter what the version in package.json is pointing to. 

Just briefly looking through the source code it seems like typescript-workspace-plugin will have the same problem that we have using 'paths'.    

Is this true?

Cheers,
Rene

**Comment by spion** [comment]
Yes its true. We've since moved away from this module, using it only as a transitional one. Additionally since this was released typescript added project references which should help make things easier.

https://www.typescriptlang.org/docs/handbook/project-references.html
